name: 'My Custom Action'
author: 'Akshaya'
description: 'This is a sample action that demonstrates metadata syntax and inputs.'

inputs:
  input1:
    description: 'This is the first input'
    required: true
    default: 'default value'
  input2:
    description: 'This is the second input'
    required: false
    default: 'another default value'

runs:
  using: 'node12'
  steps:
    - name: Install dependencies
      shell: bash 
      run: |
        npm install  
    
    - name: Run the action
      shell: node  
      run: node index.js
