name: Hello World Workflow

on:
  workflow_dispatch:  

jobs:
  hello-world:
    runs-on: ubuntu-latest

  
    name: Hello World Workflow - Triggered by ${{ github.actor }}

    steps:
    - name: Print Hello World
      run: echo "Hello, World! Triggered by ${{ github.actor }}"
