name: Hello World Workflow

on:
  pull_request_review:
    types:
      - submitted

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello World
      run: echo "Hello, World!"

