name: Log and Set Workflow Variables

on:
  push:
    branches:
      - main

jobs:
  log-and-set-user:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log GitHub Context
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"

      - name: Set USER workflow variable
        run: |
          echo "USER=${{ github.actor }}" >> $GITHUB_ENV

      - name: Print USER variable
        run: echo "The USER variable is set to ${{ env.USER }}"
