name: Docker Action Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t my-docker-action .

      - name: Run Docker action
        id: run-my-docker-action
        run: |
          docker run --rm my-docker-action
        with:
          input1: 'Hello'
          input2: 'World'

      - name: Display action output
        run: echo "The combined result is ${{ steps.run-my-docker-action.outputs.combinedResult }}"
