name: Terraform Apply

on:
  workflow_dispatch:
  
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.3.0"

    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        region: ${{ secrets.AWS_REGION }}
        role-session-name: github-actions-session

    - name: Install Terraform dependencies
      run: |
        terraform init -backend-config="path=main.tf"  

    - name: Run Terraform plan for main.tf
      run: |
        terraform plan -out=tfplan main.tf  

    - name: Apply Terraform changes for main.tf
      run: |
        terraform apply -auto-approve tfplan  
