name: Terraform Apply

on:
  workflow_dispatch:

permissions:
  id-token: write  # This grants the GitHub Actions workflow permission to use OIDC

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.3.0"

    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}
        role-session-name: github-actions-session

    - name: Install Terraform dependencies
      run: |
        terraform init -backend-config="path=main.tf"

    - name: Run Terraform plan
      run: |
        terraform plan -out=tfplan main.tf

    - name: Apply Terraform changes
      run: |
        terraform apply -auto-approve tfplan
