# first-workflow.yml
name: First Workflow (Reusable)

on:
  workflow_call:  # Triggered when called by another workflow
    inputs:
      message:
        description: 'The message to display'
        required: true
        type: string

jobs:
  display_message:
    runs-on: ubuntu-latest
    steps:
      - name: Display the message
        run: echo "${{ inputs.message }}"  # Display the input message
