name: Functions Example

on:
  push:
    branches:
      - main

jobs:
  functions-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Convert GitHub Context to JSON
        run: |
          echo "GitHub context as JSON: ${{ toJson(github) }}"
      
      - name: Check if repository name contains 'GitHub'
        run: |
          if [[ ${{ contains(github.repository, 'GitHub') }} == 'true' ]]; then
            echo "The repository name contains 'GitHub'"
          else
            echo "The repository name does not contain 'GitHub'"
          fi

      - name: Check if repository name starts with 'Aki19'
        run: |
          if [[ ${{ startsWith(github.repository, 'Aki19') }} == 'true' ]]; then
            echo "The repository name starts with 'Aki19'"
          else
            echo "The repository name does not start with 'Aki19'"
          fi

      - name: Check if repository name ends with 'GitHub-Practice'
        run: |
          if [[ ${{ endsWith(github.repository, 'GitHub-Practice') }} == 'true' ]]; then
            echo "The repository name ends with 'GitHub-Practice'"
          else
            echo "The repository name does not end with 'GitHub-Practice'"
          fi

      - name: Format a message with GitHub context
        run: |
          formatted_message="${{ format('Hello, {}! You pushed to the {} repository.', github.actor, github.repository) }}"
          echo "Formatted message: $formatted_message"

      - name: Join GitHub context values (actor, event name)
        run: |
          joined_context="${{ join(', ', format('Actor: {}', github.actor), format('Event: {}', github.event_name), format('Repository: {}', github.repository)) }}"
          echo "Joined GitHub context: $joined_context"

      - name: Parse JSON string and access GitHub context values
        run: |
          echo "Repository name (from parsed JSON): ${{ fromJson(toJson(github)).repository }}"
          echo "Actor name (from parsed JSON): ${{ fromJson(toJson(github)).actor }}"

      - name: Hash the README file
        run: |
          file_hash="${{ hashFiles('README.md') }}"
          echo "Hash of README.md: $file_hash"
