name: Inputs Context Demo

on:
  workflow_dispatch:
    inputs:
      debug:
        default: "false"
        type: boolean

jobs:
  show-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs
        run: echo "Debug Mode: ${{ inputs.debug }}"
