name: Inputs Context Demo
run-name: Inputs | Debug - ${{ inputs.debug }}
on:
  workflow_dispatch:
    inputs:
      debug:
        required: false
        default: "false"
        type: boolean

jobs:
  show-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs
        run: echo "Debug Mode: ${{ inputs.debug }}"
