name: Log GitHub Context and Set Environment Variables

on:
  push:
    branches:
      - main
      

jobs:
  log-and-set-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log GitHub Context
        run: |
          echo "Actor: ${{ github.actor }}"
          echo "Ref: ${{ github.ref }}"
          echo "Event Name: ${{ github.event_name }}"

      - name: Set GIT_BRANCH Environment Variable
        run: |
          echo "GIT_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'

      - name: Show GIT_BRANCH
        run: echo "The GIT_BRANCH environment variable is set to ${{ env.GIT_BRANCH }}"
