name: Manual Trigger Workflow

on:
  workflow_dispatch:  # Triggered manually from the GitHub UI

jobs:
  display_message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Display Welcome Message
      run: echo "Welcome to the manual trigger workflow!"

    - name: Display Goodbye Message
      run: echo "Goodbye from the manual trigger workflow!"
