# second-workflow.yml
name: Second Workflow (Triggering)

on:
  workflow_dispatch:  # This is triggered manually from the GitHub UI

jobs:
  trigger_first_workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Call the First Workflow
      uses: ./.github/workflows/first-workflow.yml  # Reference to the first workflow file
      with:
        message: "This is the message passed to the first workflow!"  # Pass message input
