name: Matrix Demo

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [14, 16]

    steps:
      - name: Print Matrix Context
        run: |
          echo "Running on OS: ${{ matrix.os }}"
          echo "Using Node.js version: ${{ matrix.node-version }}"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run Tests
        run: |
          echo "Running tests on ${{ matrix.os }} with Node.js ${{ matrix.node-version }}"
