name: metadata Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      input_1:
        description: 'Enter the first input (required)'
        required: true
        default: 'default_value_1'
      input_2:
        description: 'Enter the second input (optional)'
        required: false
        default: 'default_value_2'

jobs:
  example_job:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  

      - name: Run Custom Script
        id: run_script
        run: |
          echo "Running the workflow with input_1: ${{ github.event.inputs.input_1 }}"
          echo "Running the workflow with input_2: ${{ github.event.inputs.input_2 }}"
          echo "Output generated"
        outputs:
          output_1: "Success"  # Example output

      - name: Set Timestamp Output
        id: set_output
        run: echo "::set-output name=output_2::$(date +'%Y-%m-%d %H:%M:%S')"
        outputs:
          output_2: ${{ steps.set_output.outputs.output_2 }}

    outputs:
      # Reference the outputs defined in individual steps
      output_1: ${{ steps.run_script.outputs.output_1 }}
      output_2: ${{ steps.set_output.outputs.output_2 }}
