name: meta data for js

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run my custom action
        uses: ./  # Uses the custom action in the current repo

      - name: Display action output
        run: echo "The combined result is ${{ steps.run-my-custom-action.outputs.combinedResult }}"
