name: 'metadata Workflow'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run my custom action
      uses: ./
      with:
        input1: 'Hello World'
        input2: 'Optional value'
