name: 'metadata Workflow'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run my custom action
      uses: ./  
      with:
        input1: 'Hello'
        input2: 'World'

    - name: Display action output
      run: echo "The combined result is ${{ steps.run-my-custom-action.outputs.combinedResult }}"
