name: Object Filter with jq Example

on:
  push:
    branches:
      - main

jobs:
  object-filter-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Define Objects
        id: define_objects
        run: |
          objects='[{"name": "Object1", "status": "active"}, {"name": "Object2", "status": "inactive"}, {"name": "Object3", "status": "active"}]'
          echo "Objects: $objects"
          echo "::set-output name=objects::$objects"

      - name: Filter Active Objects using jq
        id: filter_active
        run: |
          echo "Filtering objects where status == active"
          active_objects=$(echo "${{ steps.define_objects.outputs.objects }}" | jq '[.[] | select(.status == "active")]')
          echo "Active objects: $active_objects"
          echo "::set-output name=active_objects::$active_objects"

      - name: Display Filtered Active Objects
        run: |
          echo "Filtered Active Objects: ${{ steps.filter_active.outputs.active_objects }}"
