name: Object Filter with * Operator

on:
  push:
    branches:
      - main

jobs:
  object-filter-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Define Objects
        id: define_objects
        run: |
          objects='[
            {"name": "Object1", "status": "active"},
            {"name": "Object2", "status": "inactive"},
            {"name": "Object3", "status": "active"}
          ]'
          echo "::set-output name=objects::$objects"

      - name: Filter Objects with * Operator
        run: |
          # Using the * operator to loop through the objects array and filter by status
          active_objects="${{ fromJson(steps.define_objects.outputs.objects) }}"
          active_items="${{ active_objects[*] }}"
          echo "Filtered Objects: $active_items"
