name: Secrets Demo

on:
  push:
    branches:
      - main
      
jobs:
  show-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Access secret
        run: |
          echo " secret is ${{ secrets.MY_SECRET }} "
          

      
