name: Test Self-hosted Runner

on:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print Hello World
        run: echo "Hello, World from the Self-hosted Runner!"
