name: Status Check Example

on:
  push:
    branches:
      - main

jobs:
  status-check-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Step 1 - Success Step
        id: step1
        run: |
          echo "This step will always succeed."
      
      - name: Step 2 - Failure Step
        id: step2
        run: |
          echo "This step will fail."
          exit 1  # Simulating failure

      - name: Step 3 - Success Check
        run: |
          echo "Previous steps were successful."
        if: success()  # This will run only if all previous steps succeeded

      - name: Step 4 - Failure Check
        run: |
          echo "At least one previous step has failed."
        if: failure()  # This will run only if any previous step failed

      - name: Step 5 - Always Run Check
        run: |
          echo "This step runs regardless of previous step results."
        if: always()  # This will always run, regardless of success or failure

      - name: Step 6 - Always Check (Conditional on Status)
        run: |
          echo "This step runs no matter what."
        if: always()  # This will always run
