name: Terraform EC2 Instance Creation

on:
  workflow_dispatch:  

jobs:
  terraform:
    runs-on: [self-hosted, linux] 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gnupg software-properties-common
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          sudo apt-get update -y
          sudo apt-get install -y terraform

      - name: Configure AWS Credentials
        run: |
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "region = ${{ secrets.AWS_DEFAULT_REGION }}" >> ~/.aws/credentials

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve

      - name: Upload Terraform State and Logs as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: terraform-artifacts
          path: |
            terraform.tfstate
            terraform.tfstate.backup
            *.log  

